
BEGIN EXECUTE IMMEDIATE 'DROP TABLE f1_race_results CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE f1_races CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE f1_drivers CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE f1_teams CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE f1_seasons CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE f1_seasons (
  season_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year NUMBER(4) NOT NULL UNIQUE,
  champion_driver_id NUMBER,
  champion_team_id NUMBER,
  CHECK (season_year BETWEEN 1950 AND 2100)
);

CREATE TABLE f1_races (
  race_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id NUMBER NOT NULL REFERENCES f1_seasons(season_id),
  gp_code VARCHAR2(30) NOT NULL UNIQUE,
  gp_name VARCHAR2(120) NOT NULL,
  race_date DATE NOT NULL,
  country VARCHAR2(60),
  city VARCHAR2(60),
  UNIQUE (season_id, gp_name)
);

CREATE TABLE f1_teams (
  team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_code VARCHAR2(10) NOT NULL UNIQUE,
  name VARCHAR2(100) NOT NULL UNIQUE,
  country VARCHAR2(60),
  engine VARCHAR2(60)
);

CREATE TABLE f1_drivers (
  driver_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_code VARCHAR2(10) NOT NULL UNIQUE,
  team_id NUMBER NOT NULL REFERENCES f1_teams(team_id),
  first_name VARCHAR2(60) NOT NULL,
  last_name VARCHAR2(60) NOT NULL,
  country VARCHAR2(60),
  birth_date DATE
);

CREATE TABLE f1_race_results (
  result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id NUMBER NOT NULL REFERENCES f1_races(race_id),
  driver_id NUMBER NOT NULL REFERENCES f1_drivers(driver_id),
  status VARCHAR2(10) NOT NULL,
  position NUMBER(2),
  points NUMBER(3) DEFAULT 0 NOT NULL,
  fastest_lap CHAR(1) DEFAULT 'N' NOT NULL,
  CHECK (status IN ('FINISH','DNF','DSQ')),
  CHECK (fastest_lap IN ('Y','N')),
  CHECK (points >= 0),
  UNIQUE (race_id, driver_id)
);

CREATE INDEX ix_f1_results_race   ON f1_race_results(race_id);
CREATE INDEX ix_f1_results_driver ON f1_race_results(driver_id);
CREATE INDEX ix_f1_drivers_team   ON f1_drivers(team_id);

INSERT INTO f1_seasons(season_year) VALUES (2026);

INSERT INTO f1_teams(team_code, name, country, engine) VALUES ('RBR', 'Red Bull Racing', 'Austria', 'Honda');
INSERT INTO f1_teams(team_code, name, country, engine) VALUES ('FER', 'Ferrari', 'Italy', 'Ferrari');
INSERT INTO f1_teams(team_code, name, country, engine) VALUES ('MER', 'Mercedes', 'Germany', 'Mercedes');
INSERT INTO f1_teams(team_code, name, country, engine) VALUES ('MCL', 'McLaren', 'United Kingdom', 'Mercedes');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('VER', (SELECT team_id FROM f1_teams WHERE team_code='RBR'), 'Max', 'Verstappen', 'Netherlands', DATE '1997-09-30');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('PER', (SELECT team_id FROM f1_teams WHERE team_code='RBR'), 'Sergio', 'Perez', 'Mexico', DATE '1990-01-26');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('LEC', (SELECT team_id FROM f1_teams WHERE team_code='FER'), 'Charles', 'Leclerc', 'Monaco', DATE '1997-10-16');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('SAI', (SELECT team_id FROM f1_teams WHERE team_code='FER'), 'Carlos', 'Sainz', 'Spain', DATE '1994-09-01');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('HAM', (SELECT team_id FROM f1_teams WHERE team_code='MER'), 'Lewis', 'Hamilton', 'United Kingdom', DATE '1985-01-07');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('RUS', (SELECT team_id FROM f1_teams WHERE team_code='MER'), 'George', 'Russell', 'United Kingdom', DATE '1998-02-15');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('NOR', (SELECT team_id FROM f1_teams WHERE team_code='MCL'), 'Lando', 'Norris', 'United Kingdom', DATE '1999-11-13');

INSERT INTO f1_drivers(driver_code, team_id, first_name, last_name, country, birth_date)
VALUES ('PIA', (SELECT team_id FROM f1_teams WHERE team_code='MCL'), 'Oscar', 'Piastri', 'Australia', DATE '2001-04-06');

INSERT INTO f1_races(season_id, gp_code, gp_name, race_date, country, city)
VALUES ((SELECT season_id FROM f1_seasons WHERE season_year = 2026),
        'BAHRAIN_2026', 'Bahrain GP', DATE '2026-03-08', 'Bahrain', 'Sakhir');

INSERT INTO f1_races(season_id, gp_code, gp_name, race_date, country, city)
VALUES ((SELECT season_id FROM f1_seasons WHERE season_year = 2026),
        'EMILIA_2026', 'Emilia Romagna GP', DATE '2026-05-17', 'Italy', 'Imola');

INSERT INTO f1_races(season_id, gp_code, gp_name, race_date, country, city)
VALUES ((SELECT season_id FROM f1_seasons WHERE season_year = 2026),
        'MONACO_2026', 'Monaco GP', DATE '2026-05-24', 'Monaco', 'Monte Carlo');

COMMIT;

SELECT COUNT(*) AS seasons FROM f1_seasons;
SELECT COUNT(*) AS teams   FROM f1_teams;
SELECT COUNT(*) AS drivers FROM f1_drivers;
SELECT COUNT(*) AS races   FROM f1_races;
SELECT COUNT(*) AS results FROM f1_race_results;